#!/bin/sh
echo "pre_start_python: starting"

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rh/postgresql92/root/usr/lib64/

python $OPENSHIFT_REPO_DIR/manage.py collectstatic --noinput

echo "pre_start_python: done!"